
/**
 * This file is generated by Sencha Cmd and should NOT be edited.  It is 
 * provided to support globbing requires, custom xtypes, and other 
 * metadata-driven class system features 
 */
Ext.Loader.addClassPathMappings({
  "SmartSolutions": "app",
  "SmartSolutions.controller.categories.MainCategoriesController": "app/controller/Categories/MainCategoriesController.js",
  "Ext": "ext/src",
  "Ext.rtl.EventObjectImpl": "ext/src/rtl/EventObject.js"
});
Ext.ClassManager.addNameAlternateMappings({
  "SmartSolutions.model.User": [],
  "Ext.ux.BoxReorderer": [],
  "SmartSolutions.view.solutions.NewSolutionView": [],
  "Ext.ux.grid.filter.Filter": [],
  "Ext.ux.GroupTabRenderer": [],
  "SmartSolutions.view.categories.SelectCategoryView": [],
  "SmartSolutions.model.ImageItem": [],
  "SmartSolutions.view.login.ForgotPassword": [],
  "Ext.ux.ajax.DataSimlet": [],
  "Ext.ux.grid.TransformGrid": [],
  "Ext.ux.FieldReplicator": [],
  "Ext.ux.grid.filter.ListFilter": [],
  "SmartSolutions.view.login.Login": [],
  "SmartSolutions.view.Header": [],
  "SmartSolutions.store.Categories": [],
  "Ext.ux.ajax.XmlSimlet": [],
  "Ext.ux.event.Driver": [],
  "SmartSolutions.controller.solutions.CreateSolutionController": [],
  "Ext.ux.dd.PanelFieldDragZone": [],
  "Ext.ux.DataView.DragSelector": [],
  "Ext.ux.grid.menu.ListMenu": [],
  "Ext.ux.GMapPanel": [],
  "SmartSolutions.controller.login.LoginController": [],
  "Ext.ux.form.MultiSelect": [
    "Ext.ux.Multiselect"
  ],
  "Ext.ux.DataView.LabelEditor": [],
  "Ext.ux.GroupTabPanel": [],
  "Ext.ux.grid.filter.StringFilter": [],
  "Ext.ux.statusbar.ValidationStatus": [],
  "SmartSolutions.view.Viewport": [],
  "Ext.ux.layout.Center": [],
  "SmartSolutions.view.solutions.NewSolutionSave": [],
  "Ext.ux.PreviewPlugin": [],
  "Ext.ux.DataView.Animated": [],
  "Ext.ux.ajax.SimXhr": [],
  "Ext.ux.event.RecorderManager": [],
  "Ext.ux.ProgressBarPager": [],
  "SmartSolutions.view.login.Register": [],
  "Ext.ux.CellDragDrop": [],
  "SmartSolutions.defaults.Constants": [],
  "SmartSolutions.controller.categories.MainCategoriesController": [],
  "Ext.ux.statusbar.StatusBar": [
    "Ext.ux.StatusBar"
  ],
  "Ext.ux.ajax.Simlet": [],
  "Ext.ux.SlidingPager": [],
  "SmartSolutions.model.Solution": [],
  "Ext.ux.TabReorderer": [],
  "Ext.ux.grid.filter.NumericFilter": [],
  "SmartSolutions.view.categories.CategoriesView": [],
  "SmartSolutions.controller.MainController": [],
  "Ext.ux.grid.menu.RangeMenu": [],
  "Ext.ux.RowExpander": [],
  "Ext.ux.event.Recorder": [],
  "Ext.ux.event.Player": [],
  "SmartSolutions.view.categories.CategoriesListView": [],
  "SmartSolutions.controller.login.ForgotPasswordController": [],
  "SmartSolutions.controller.components.SearchController": [],
  "Ext.ux.ajax.SimManager": [],
  "Ext.ux.grid.filter.BooleanFilter": [],
  "Ext.ux.ToolbarDroppable": [],
  "SmartSolutions.store.CategoryItems": [],
  "Ext.ux.event.Maker": [],
  "SmartSolutions.view.components.SearchView": [],
  "SmartSolutions.view.solutions.CreateYourSolutionView": [],
  "Ext.ux.TabScrollerMenu": [],
  "SmartSolutions.view.login.LoginRegister": [],
  "SmartSolutions.view.solutions.YourSolutionsView": [],
  "Ext.ux.IFrame": [],
  "Ext.ux.DataView.Draggable": [],
  "Ext.ux.TabCloseMenu": [],
  "Ext.ux.form.SearchField": [],
  "Ext.ux.dd.CellFieldDropZone": [],
  "SmartSolutions.controller.solutions.YourSolutionsController": [],
  "SmartSolutions.controller.login.RegisterController": [],
  "Ext.ux.LiveSearchGridPanel": [],
  "SmartSolutions.store.Users": [],
  "Ext.ux.DataTip": [],
  "Ext.ux.grid.filter.DateFilter": [],
  "Ext.ux.grid.filter.DateTimeFilter": [],
  "SmartSolutions.store.Solutions": [],
  "Ext.ux.TreePicker": [],
  "Ext.ux.form.ItemSelector": [
    "Ext.ux.ItemSelector"
  ],
  "Ext.ux.ajax.JsonSimlet": [],
  "SmartSolutions.model.Category": [],
  "Ext.ux.Spotlight": [],
  "Ext.ux.grid.FiltersFeature": [],
  "SmartSolutions.view.solutions.SolutionsView": [],
  "Ext.ux.data.PagingMemoryProxy": [
    "Ext.data.PagingMemoryProxy"
  ]
});
Ext.ClassManager.addNameAliasMappings({
  "SmartSolutions.model.User": [],
  "Ext.ux.BoxReorderer": [],
  "SmartSolutions.view.solutions.NewSolutionView": [
    "widget.newsolutionview"
  ],
  "Ext.ux.grid.filter.Filter": [],
  "Ext.ux.GroupTabRenderer": [
    "plugin.grouptabrenderer"
  ],
  "SmartSolutions.view.categories.SelectCategoryView": [
    "widget.selectcategoryview"
  ],
  "SmartSolutions.model.ImageItem": [],
  "SmartSolutions.view.login.ForgotPassword": [
    "widget.forgotPassword"
  ],
  "Ext.ux.ajax.DataSimlet": [],
  "Ext.ux.grid.TransformGrid": [],
  "Ext.ux.FieldReplicator": [],
  "Ext.ux.grid.filter.ListFilter": [
    "gridfilter.list"
  ],
  "SmartSolutions.view.login.Login": [
    "widget.login"
  ],
  "SmartSolutions.view.Header": [
    "widget.smartsolutionsheader"
  ],
  "SmartSolutions.store.Categories": [],
  "Ext.ux.ajax.XmlSimlet": [
    "simlet.xml"
  ],
  "Ext.ux.event.Driver": [],
  "SmartSolutions.controller.solutions.CreateSolutionController": [],
  "Ext.ux.dd.PanelFieldDragZone": [],
  "Ext.ux.DataView.DragSelector": [],
  "Ext.ux.grid.menu.ListMenu": [],
  "Ext.ux.GMapPanel": [
    "widget.gmappanel"
  ],
  "SmartSolutions.controller.login.LoginController": [],
  "Ext.ux.form.MultiSelect": [
    "widget.multiselect",
    "widget.multiselectfield"
  ],
  "Ext.ux.DataView.LabelEditor": [],
  "Ext.ux.GroupTabPanel": [
    "widget.grouptabpanel"
  ],
  "Ext.ux.grid.filter.StringFilter": [
    "gridfilter.string"
  ],
  "Ext.ux.statusbar.ValidationStatus": [],
  "SmartSolutions.view.Viewport": [],
  "Ext.ux.layout.Center": [
    "layout.ux.center"
  ],
  "SmartSolutions.view.solutions.NewSolutionSave": [
    "widget.newsolutionsave"
  ],
  "Ext.ux.PreviewPlugin": [
    "plugin.preview"
  ],
  "Ext.ux.DataView.Animated": [],
  "Ext.ux.ajax.SimXhr": [],
  "Ext.ux.event.RecorderManager": [
    "widget.eventrecordermanager"
  ],
  "Ext.ux.ProgressBarPager": [],
  "SmartSolutions.view.login.Register": [
    "widget.register"
  ],
  "Ext.ux.CellDragDrop": [
    "plugin.celldragdrop"
  ],
  "SmartSolutions.defaults.Constants": [],
  "SmartSolutions.controller.categories.MainCategoriesController": [],
  "Ext.ux.statusbar.StatusBar": [
    "widget.statusbar"
  ],
  "Ext.ux.ajax.Simlet": [
    "simlet.basic"
  ],
  "Ext.ux.SlidingPager": [],
  "SmartSolutions.model.Solution": [],
  "Ext.ux.TabReorderer": [],
  "Ext.ux.grid.filter.NumericFilter": [
    "gridfilter.numeric"
  ],
  "SmartSolutions.view.categories.CategoriesView": [
    "widget.categoriesview"
  ],
  "SmartSolutions.controller.MainController": [],
  "Ext.ux.grid.menu.RangeMenu": [],
  "Ext.ux.RowExpander": [],
  "Ext.ux.event.Recorder": [],
  "Ext.ux.event.Player": [],
  "SmartSolutions.view.categories.CategoriesListView": [
    "widget.categorieslist"
  ],
  "SmartSolutions.controller.login.ForgotPasswordController": [],
  "SmartSolutions.controller.components.SearchController": [],
  "Ext.ux.ajax.SimManager": [],
  "Ext.ux.grid.filter.BooleanFilter": [
    "gridfilter.boolean"
  ],
  "Ext.ux.ToolbarDroppable": [],
  "SmartSolutions.store.CategoryItems": [],
  "Ext.ux.event.Maker": [],
  "SmartSolutions.view.components.SearchView": [
    "widget.search"
  ],
  "SmartSolutions.view.solutions.CreateYourSolutionView": [
    "widget.createyoursolution"
  ],
  "Ext.ux.TabScrollerMenu": [
    "plugin.tabscrollermenu"
  ],
  "SmartSolutions.view.login.LoginRegister": [
    "widget.loginRegister"
  ],
  "SmartSolutions.view.solutions.YourSolutionsView": [
    "widget.yoursolutionsview"
  ],
  "Ext.ux.IFrame": [
    "widget.uxiframe"
  ],
  "Ext.ux.DataView.Draggable": [],
  "Ext.ux.TabCloseMenu": [
    "plugin.tabclosemenu"
  ],
  "Ext.ux.form.SearchField": [
    "widget.searchfield"
  ],
  "Ext.ux.dd.CellFieldDropZone": [],
  "SmartSolutions.controller.solutions.YourSolutionsController": [],
  "SmartSolutions.controller.login.RegisterController": [],
  "Ext.ux.LiveSearchGridPanel": [],
  "SmartSolutions.store.Users": [],
  "Ext.ux.DataTip": [
    "plugin.datatip"
  ],
  "Ext.ux.grid.filter.DateFilter": [
    "gridfilter.date"
  ],
  "Ext.ux.grid.filter.DateTimeFilter": [
    "gridfilter.datetime"
  ],
  "SmartSolutions.store.Solutions": [],
  "Ext.ux.TreePicker": [
    "widget.treepicker"
  ],
  "Ext.ux.form.ItemSelector": [
    "widget.itemselector",
    "widget.itemselectorfield"
  ],
  "Ext.ux.ajax.JsonSimlet": [
    "simlet.json"
  ],
  "SmartSolutions.model.Category": [],
  "Ext.ux.Spotlight": [],
  "Ext.ux.grid.FiltersFeature": [
    "feature.filters"
  ],
  "SmartSolutions.view.solutions.SolutionsView": [
    "widget.solutionsview"
  ],
  "Ext.ux.data.PagingMemoryProxy": [
    "proxy.pagingmemory"
  ]
});
